import React from "react";
import Posts from "./Posts";

function Feed() {
  return (
    <div className="feed">
      <div>
        <h2>Competition Feed</h2>
        <Posts />
        <p>Notifications, new participants, new workouts, changes to the leaderboard, commentary generated by AI, user posts and comments</p>
      </div>
    </div>
  );
}

export default Feed;
