services:

  db:
    image: postgres
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    working_dir: /api

  redis:
    image: 'redis:7-alpine'
    command: redis-server
    ports:
      - '6379:6379'

  helper:
    image: alpine
    command: sh -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    privileged: true

  api:
    image: rails-api-backend
    build: api
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    working_dir: /api
    depends_on:
      - db
      - redis

  client:
    build: client
    image: react-client-frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - "4000:4000"
    working_dir: /client
    volumes:
      - ./client:/client
    environment:
      POSTGRES_PASSWORD: password
